### ISSUE TITLE
Server Error when trying to connect

### ISSUE THREAD

**Issue by crimsonpixel** [jdaehne/socialFeedMODX#12]
I've used socialfeed with great success but there seems to be an issue when a site moves from a dev site to a live location.  I have tried to reset the feed by creating a new channel connection but I'm getting a 500 | Server Error when it tries to link to Instagram.

I have revoked the original connection on Instagram so trying to create a new link but can't seem to get it to work and channel shows as unauth.

Also would be good to delete old Feeds which are no longer required.  I see how you can remove a channel but not a feed.

This is happening on a couple of site, one built with MODX 2.8.1 site and other 2.8.2 site

**Comment by crimsonpixel** [comment]
I've retried again today to connect to Instagram for my clients feed but still having the same 500 | Server Error.  The feed needs to be re-instated as soon as possible.  If you need access to the site in question I am happy to provide that.

In the Instagram account that I am trying to connect to, it does show that the SocialFeed app has been allowed, but even when I run the domain.com/assets/components/socialfeed/cron.php the images do not update.  And in the SocialFeed website it shows as unauth.

**Comment by bennyb** [comment]
@crimsonpixel any luck with this, most have my feeds have stopped working and just tried to delete and create a new one and getting the same issue as you

**Comment by crimsonpixel** [comment]
Unfortunately not.  Hoping we might get a response soon.

**Comment by QuentinFaulkner** [comment]
@crimsonpixel, @bennyb - I've not got an media updates since about the 17th May and also get the same 500 | Server Error issues on creating new Channels. Fingers crossed it gets resolved soon.

**Comment by crimsonpixel** [comment]
@bennyb @QuentinFaulkner - I have emailed @jdaehne directly so hopefully we will hear back soon to get this updated as clients are beginning to grumble...

**Comment by jdaehne** [comment]
​sorry for the issue with social feed. Instagram had some changes in their api we had to implement into socialFeed. We fixed that - the feeds and new feeds should work again.
​
​Instagram-Feeds need to reauthenticate every 60 days. SocialFeed does that automatically for you. But if the reauthentication was done in the last few days your account may failed and has to be reconected to socialfeed. You can check that by going to your channel: https://www.socialfeed.pro/channels
​If it shows a label "active" - everything is good. Otherwise you can just reconnect your account by copy and visit the "Connect-Link" of the channel.
​
​Sorry for the issues - but because this is a free Service we are not as fast as we would like to. Thanks a lot for your reports. I hope you can still enjoy this service/extra.
​
​Best regards
​Jan
